# Generated by Django 4.2.4 on 2023-10-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
    ]
