# Generated by Django 4.2.4 on 2023-09-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
