# Generated by Django 4.2.4 on 2023-09-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Создание'),
        ),
    ]
