# Generated by Django 4.2.4 on 2023-09-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pics/', verbose_name='Изображение'),
        ),
    ]
