# Generated by Django 4.2.4 on 2023-09-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.TextField(blank=True, max_length=11, null=True, verbose_name='Телефон'),
        ),
    ]
