# Generated by Django 4.2.4 on 2023-09-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='product',
        ),
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='versions', to='main.product'),
        ),
    ]
