# Generated by Django 4.2.4 on 2023-09-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_version_flag_of_the_current_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='product',
        ),
    ]
